// generated by goplater -type=OrderIType -transform=snake -tprefix=false; DO NOT EDIT
package payment

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrOrderITypeInvalid = errors.New("OrderIType is invalid")

	defOrderITypeNameToValue = map[string]OrderIType{
		"I": OrderITypeItem,
		"S": OrderITypeShipping,
	}

	defOrderITypeValueToName = map[OrderIType]string{
		OrderITypeItem:     "I",
		OrderITypeShipping: "S",
	}
)

// String is generated so OrderIType satisfies fmt.Stringer.
func (r OrderIType) String() string {
	s, ok := defOrderITypeValueToName[r]
	if !ok {
		return fmt.Sprintf("OrderIType(%d)", r)
	}
	return s
}

// Validate verifies that value is predefined for OrderIType.
func (r OrderIType) Validate() error {
	_, ok := defOrderITypeValueToName[r]
	if !ok {
		return ErrOrderITypeInvalid
	}
	return nil
}

// MarshalJSON is generated so OrderIType satisfies json.Marshaler.
func (r OrderIType) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := defOrderITypeValueToName[r]
	if !ok {
		return nil, fmt.Errorf("OrderIType(%d) is invalid value", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so OrderIType satisfies json.Unmarshaler.
func (r *OrderIType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OrderIType: should be a string, got %s", string(data))
	}
	v, ok := defOrderITypeNameToValue[s]
	if !ok {
		return fmt.Errorf("OrderIType(%q) is invalid value", s)
	}
	*r = v
	return nil
}

// Value is generated so OrderIType satisfies db row driver.Valuer.
func (r OrderIType) Value() (driver.Value, error) {
	j, err := json.Marshal(r)
	return j, err
}

// Value is generated so OrderIType satisfies db row driver.Scanner.
func (r *OrderIType) Scan(src interface{}) error {
	switch src.(type) {
	case string:
		val, ok := defOrderITypeNameToValue[src.(string)]
		if !ok {
			return errors.New("OrderIType: can't unmarshal column data")
		}
		*r = val
		return nil
	case []byte:
		source := src.([]byte)
		var i OrderIType
		err := json.Unmarshal(source, &i)
		if err != nil {
			return errors.New("OrderIType: can't unmarshal column data")
		}

		*r = i
		return nil
	case int, int8, int32, int64, uint, uint8, uint32, uint64:
		ni := sql.NullInt64{}
		err := ni.Scan(src)
		if err != nil {
			return errors.New("OrderIType: can't scan column data into int64")
		}

		*r = OrderIType(ni.Int64)
		return nil
	}
	return errors.New("OrderIType: invalid type")
}
