// generated by goplater -type=TxType -transform=snake -tprefix=false; DO NOT EDIT
package payment

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrTxTypeInvalid = errors.New("TxType is invalid")

	defTxTypeNameToValue = map[string]TxType{
		"I": TxTypeIn,
		"T": TxTypeTransfer,
		"O": TxTypeOut,
	}

	defTxTypeValueToName = map[TxType]string{
		TxTypeIn:       "I",
		TxTypeTransfer: "T",
		TxTypeOut:      "O",
	}
)

// String is generated so TxType satisfies fmt.Stringer.
func (r TxType) String() string {
	s, ok := defTxTypeValueToName[r]
	if !ok {
		return fmt.Sprintf("TxType(%d)", r)
	}
	return s
}

// Validate verifies that value is predefined for TxType.
func (r TxType) Validate() error {
	_, ok := defTxTypeValueToName[r]
	if !ok {
		return ErrTxTypeInvalid
	}
	return nil
}

// MarshalJSON is generated so TxType satisfies json.Marshaler.
func (r TxType) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := defTxTypeValueToName[r]
	if !ok {
		return nil, fmt.Errorf("TxType(%d) is invalid value", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so TxType satisfies json.Unmarshaler.
func (r *TxType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TxType: should be a string, got %s", string(data))
	}
	v, ok := defTxTypeNameToValue[s]
	if !ok {
		return fmt.Errorf("TxType(%q) is invalid value", s)
	}
	*r = v
	return nil
}

// Value is generated so TxType satisfies db row driver.Valuer.
func (r TxType) Value() (driver.Value, error) {
	j, err := json.Marshal(r)
	return j, err
}

// Value is generated so TxType satisfies db row driver.Scanner.
func (r *TxType) Scan(src interface{}) error {
	switch src.(type) {
	case string:
		val, ok := defTxTypeNameToValue[src.(string)]
		if !ok {
			return errors.New("TxType: can't unmarshal column data")
		}
		*r = val
		return nil
	case []byte:
		source := src.([]byte)
		var i TxType
		err := json.Unmarshal(source, &i)
		if err != nil {
			return errors.New("TxType: can't unmarshal column data")
		}

		*r = i
		return nil
	case int, int8, int32, int64, uint, uint8, uint32, uint64:
		ni := sql.NullInt64{}
		err := ni.Scan(src)
		if err != nil {
			return errors.New("TxType: can't scan column data into int64")
		}

		*r = TxType(ni.Int64)
		return nil
	}
	return errors.New("TxType: invalid type")
}
