// generated by goplater -type=DocumentStatus -transform=none -tprefix=false; DO NOT EDIT
package kyc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
)

func init() {
	// stub usage of json for situation when
	// (Un)MarshalJSON methods will be omitted
	_ = json.Delim('s')

	// stub usage of sql/driver for situation when
	// Scan/Value methods will be omitted
	_ = driver.Bool
	_ = sql.LevelDefault
}

var ErrDocumentStatusInvalid = errors.New("DocumentStatus is invalid")

func init() {
	var v DocumentStatus
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		defDocumentStatusNameToValue = map[string]DocumentStatus{
			interface{}(DocumentStatusNEW).(fmt.Stringer).String(): DocumentStatusNEW,
			interface{}(DocumentStatusVLD).(fmt.Stringer).String(): DocumentStatusVLD,
			interface{}(DocumentStatusWAR).(fmt.Stringer).String(): DocumentStatusWAR,
			interface{}(DocumentStatusERR).(fmt.Stringer).String(): DocumentStatusERR,
		}
	}
}

var defDocumentStatusNameToValue = map[string]DocumentStatus{
	"NEW": DocumentStatusNEW,
	"VLD": DocumentStatusVLD,
	"WAR": DocumentStatusWAR,
	"ERR": DocumentStatusERR,
}

var defDocumentStatusValueToName = map[DocumentStatus]string{
	DocumentStatusNEW: "NEW",
	DocumentStatusVLD: "VLD",
	DocumentStatusWAR: "WAR",
	DocumentStatusERR: "ERR",
}

// String is generated so DocumentStatus satisfies fmt.Stringer.
func (r DocumentStatus) String() string {
	s, ok := defDocumentStatusValueToName[r]
	if !ok {
		return fmt.Sprintf("DocumentStatus(%d)", r)
	}
	return s
}

// Validate verifies that value is predefined for DocumentStatus.
func (r DocumentStatus) Validate() error {
	_, ok := defDocumentStatusValueToName[r]
	if !ok {
		return ErrDocumentStatusInvalid
	}
	return nil
}

// MarshalJSON is generated so DocumentStatus satisfies json.Marshaler.
func (r DocumentStatus) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := defDocumentStatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("DocumentStatus(%d) is invalid value", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so DocumentStatus satisfies json.Unmarshaler.
func (r *DocumentStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DocumentStatus: should be a string, got %s", string(data))
	}
	v, ok := defDocumentStatusNameToValue[s]
	if !ok {
		return fmt.Errorf("DocumentStatus(%q) is invalid value", s)
	}
	*r = v
	return nil
}

// Value is generated so DocumentStatus satisfies db row driver.Valuer.
func (r DocumentStatus) Value() (driver.Value, error) {
	j, err := json.Marshal(r)
	return j, err
}

// Value is generated so DocumentStatus satisfies db row driver.Scanner.
func (r *DocumentStatus) Scan(src interface{}) error {
	switch src.(type) {
	case string:
		val, ok := defDocumentStatusNameToValue[src.(string)]
		if !ok {
			return errors.New("DocumentStatus: can't unmarshal column data")
		}
		*r = val
		return nil
	case []byte:
		source := src.([]byte)
		var i DocumentStatus
		err := json.Unmarshal(source, &i)
		if err != nil {
			return errors.New("DocumentStatus: can't unmarshal column data")
		}

		*r = i
		return nil
	case int, int8, int32, int64, uint, uint8, uint32, uint64:
		ni := sql.NullInt64{}
		err := ni.Scan(src)
		if err != nil {
			return errors.New("DocumentStatus: can't scan column data into int64")
		}

		*r = DocumentStatus(ni.Int64)
		return nil
	}
	return errors.New("DocumentStatus: invalid type")
}
