// generated by goplater -type=CardType,CardStatus -transform=none -tprefix=false; DO NOT EDIT
package cards

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
)

var ErrCardStatusInvalid = errors.New("CardStatus is invalid")

var defCardStatusNameToValue = map[string]CardStatus{
	"E": CardStatusExpired,
	"N": CardStatusNotVerified,
	"V": CardStatusVerified,
}

var defCardStatusValueToName = map[CardStatus]string{
	CardStatusExpired:     "E",
	CardStatusNotVerified: "N",
	CardStatusVerified:    "V",
}

// String is generated so CardStatus satisfies fmt.Stringer.
func (r CardStatus) String() string {
	s, ok := defCardStatusValueToName[r]
	if !ok {
		return fmt.Sprintf("CardStatus(%d)", r)
	}
	return s
}

// Validate verifies that value is predefined for CardStatus.
func (r CardStatus) Validate() error {
	_, ok := defCardStatusValueToName[r]
	if !ok {
		return ErrCardStatusInvalid
	}
	return nil
}

// MarshalJSON is generated so CardStatus satisfies json.Marshaler.
func (r CardStatus) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := defCardStatusValueToName[r]
	if !ok {
		return nil, fmt.Errorf("CardStatus(%d) is invalid value", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so CardStatus satisfies json.Unmarshaler.
func (r *CardStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CardStatus: should be a string, got %s", string(data))
	}
	v, ok := defCardStatusNameToValue[s]
	if !ok {
		return fmt.Errorf("CardStatus(%q) is invalid value", s)
	}
	*r = v
	return nil
}

// Value is generated so CardStatus satisfies db row driver.Valuer.
func (r CardStatus) Value() (driver.Value, error) {
	j, err := json.Marshal(r)
	return j, err
}

// Value is generated so CardStatus satisfies db row driver.Scanner.
func (r *CardStatus) Scan(src interface{}) error {
	switch src.(type) {
	case string:
		val, ok := defCardStatusNameToValue[src.(string)]
		if !ok {
			return errors.New("CardStatus: can't unmarshal column data")
		}
		*r = val
		return nil
	case []byte:
		source := src.([]byte)
		var i CardStatus
		err := json.Unmarshal(source, &i)
		if err != nil {
			return errors.New("CardStatus: can't unmarshal column data")
		}

		*r = i
		return nil
	case int, int8, int32, int64, uint, uint8, uint32, uint64:
		ni := sql.NullInt64{}
		err := ni.Scan(src)
		if err != nil {
			return errors.New("CardStatus: can't scan column data into int64")
		}

		*r = CardStatus(ni.Int64)
		return nil
	}
	return errors.New("CardStatus: invalid type")
}
