// generated by goplater -type=CardType,CardStatus -transform=none -tprefix=false; DO NOT EDIT
package cards

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
)

var ErrCardTypeInvalid = errors.New("CardType is invalid")

var defCardTypeNameToValue = map[string]CardType{
	"A": CardTypeAmExpress,
	"M": CardTypeMasterCard,
	"V": CardTypeVisa,
}

var defCardTypeValueToName = map[CardType]string{
	CardTypeAmExpress:  "A",
	CardTypeMasterCard: "M",
	CardTypeVisa:       "V",
}

// String is generated so CardType satisfies fmt.Stringer.
func (r CardType) String() string {
	s, ok := defCardTypeValueToName[r]
	if !ok {
		return fmt.Sprintf("CardType(%d)", r)
	}
	return s
}

// Validate verifies that value is predefined for CardType.
func (r CardType) Validate() error {
	_, ok := defCardTypeValueToName[r]
	if !ok {
		return ErrCardTypeInvalid
	}
	return nil
}

// MarshalJSON is generated so CardType satisfies json.Marshaler.
func (r CardType) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := defCardTypeValueToName[r]
	if !ok {
		return nil, fmt.Errorf("CardType(%d) is invalid value", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so CardType satisfies json.Unmarshaler.
func (r *CardType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CardType: should be a string, got %s", string(data))
	}
	v, ok := defCardTypeNameToValue[s]
	if !ok {
		return fmt.Errorf("CardType(%q) is invalid value", s)
	}
	*r = v
	return nil
}

// Value is generated so CardType satisfies db row driver.Valuer.
func (r CardType) Value() (driver.Value, error) {
	j, err := json.Marshal(r)
	return j, err
}

// Value is generated so CardType satisfies db row driver.Scanner.
func (r *CardType) Scan(src interface{}) error {
	switch src.(type) {
	case string:
		val, ok := defCardTypeNameToValue[src.(string)]
		if !ok {
			return errors.New("CardType: can't unmarshal column data")
		}
		*r = val
		return nil
	case []byte:
		source := src.([]byte)
		var i CardType
		err := json.Unmarshal(source, &i)
		if err != nil {
			return errors.New("CardType: can't unmarshal column data")
		}

		*r = i
		return nil
	case int, int8, int32, int64, uint, uint8, uint32, uint64:
		ni := sql.NullInt64{}
		err := ni.Scan(src)
		if err != nil {
			return errors.New("CardType: can't scan column data into int64")
		}

		*r = CardType(ni.Int64)
		return nil
	}
	return errors.New("CardType: invalid type")
}
